FROM risingstack:trusty-base

MAINTAINER Gergely Nemeth <gergely@risingstack.com>

RUN   curl -sSL https://nodejs.org/dist/{{VERSION}}/node-{{VERSION}}.tar.gz | tar -xz && \
  cd /node-{{VERSION}} && \
  ./configure --prefix=/usr && \
  make && sudo make install

WORKDIR /usr/src/node-app
