FROM alpine:3.3

MAINTAINER Gergely Nemeth <gergely@risingstack.com>

RUN apk add --update \
  binutils-gold \
  curl \
  gcc \
  g++ \
  libgcc \
  libstdc++ \
  linux-headers \
  make \
  paxctl \
  python
